all:
	g++	assembler/main.cpp assembler/assembler.cpp rest/stack.cpp -o assemb
	g++	disassembler/main.cpp disassembler/disassembler.cpp rest/read_file.cpp -o disassemb
	g++	processor/main.cpp processor/processor.cpp rest/read_file.cpp rest/stack.cpp -o proc
